name: Publish

on:
  push:
    tags:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Prepare build settings
      id: build_settings
      run: echo ::set-output name=BUILD_VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Validate tag
      run: bash -c "[[ $BUILD_VERSION =~ [0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)? ]]"
      env:
        BUILD_VERSION: ${{ steps.build_settings.outputs.BUILD_VERSION }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: Build
      run: ./gradlew build
    - name: Test
      run: ./gradlew test
    - name: Publish
      run: ./gradlew publish
      env:
        BUILD_VERSION: ${{ steps.build_settings.outputs.BUILD_VERSION }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD:  ${{ secrets.OSSRH_PASSWORD }}
        GPG_ARMORED_KEY: ${{ secrets.GPG_ARMORED_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
