name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: Test
      run: ./gradlew test
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: Publish
      run: ./gradlew clean build publish
      env:
        BUILD_VERSION: 0.0.3-SNAPSHOT
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD:  ${{ secrets.OSSRH_PASSWORD }}
        GPG_ARMORED_KEY: ${{ secrets.GPG_ARMORED_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
